repos:
  - repo: https://github.com/python/black
    rev: 23.7.0
    hooks:
      - id: black
  
  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: v0.2.2
    hooks:
      - id: auto-walrus

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args:
          - --quiet-level=2
          - --skip=.github/workflows/codespell.yml.disabled
