
[tool.pytest.ini_options]
addopts = [
    "--ignore=modules/gtest",
    "--ignore=Tools/FilterTestTool",
    "--ignore=Tools/ros2/ardupilot_dds_tests/test"
]
filterwarnings = [
    "ignore:cannot collect test class.*test_build_options:pytest.PytestCollectionWarning",
    "ignore:cannot collect test class.*test_param_upgrade:pytest.PytestCollectionWarning",
]
markers = ["linter"]
python_files = ["test_*.py", "*_test.py", "*_unittest.py", "*_unittests.py"]
pythonpath = [".", "Tools/autotest", "Tools/scripts"]
