language: python
env:
    - REPO=ethereum/pyethereum
    - REPO=pallets/jinja
    - REPO=yeleman/hamed-advanced
    - REPO=rgaudin/django-orangeapisms
    - REPO=google/yapf
    - REPO=pypa/setuptools
    - REPO=python/cpython
    - REPO=tensorflow/nmt
    - REPO=tensorflow/models
    - REPO=scikit-learn/scikit-learn
    - REPO=warner/magic-wormhole
    - REPO=scrapy/scrapy
    - REPO=HelloZeroNet/ZeroNet
    - REPO=XX-net/XX-Net
    - REPO=pallets/flask
    - REPO=DarkSand/Sasila
    - REPO=josephmisiti/awesome-machine-learning
python:
    - 2.7.13
    - 3.6.1
install:
    - pip install flake8  # pytest  # add some test later
script:
    - URL=https://github.com/${REPO}
    - git clone --depth=50 --branch=master ${URL} ~/${REPO}
    - cd ~/${REPO}
    - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
    - echo stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    - echo exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
