name: c_on_three_oses
on:
  push:
    paths:
      - '.github/workflows/c_on_three_oses.yml'
  pull_request:
    paths:
      - '.github/workflows/c_on_three_oses.yml'
  workflow_dispatch:
jobs:
  c_on_three_oses:
    strategy:
      fail-fast: false
      matrix:
        ccompiler: [gcc, clang]  #, msvc]
        os: [macos-13, macos-15, macos-latest, ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Compile with ${{ matrix.ccompiler }} on ${{ matrix.os }}
        shell: bash
        run: |
          echo "int main() { char buff[1024] = {0}; return 0; }" > initialized.c
          echo "int main() { char buff[1024]; return 0; }" > uninitialized.c
          "${{ matrix.ccompiler }}" -o initialized initialized.c
          "${{ matrix.ccompiler }}" -o uninitialized uninitialized.c
          ls -l uninitialized initialized
