name: conda_on_demand
on:
  workflow_dispatch:
    inputs:
      conda_command:
        description: 'conda command'
        required: false
jobs:
  conda_on_demand:
    name: "conda_on_demand: ${{ github.event.inputs.conda_command }}"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: conda search python
    - if: ${{ github.event.inputs.conda_command }}
      run: ${{ github.event.inputs.conda_command }}
