name: cygwin
on:
  push:
    paths:
      - '.github/workflows/cygwin.yml'
  pull_request:
    paths:
      - '.github/workflows/cygwin.yml'
  workflow_dispatch:
jobs:
  cygwin:
    # name: "${{ github.event.inputs.repo }}"
    strategy:
      fail-fast: false
      matrix:  # https://cygwin.com/packages/summary/python312.html
        cygwin_package:
          # - ""
          # - "cygiconv"  # Package 'cygiconv' not found.
          # - "cygintl"  # Package 'cygintl' not found.
          # - "libiconv2"  # Installed by default
          # - "libintl8"  # Installed by default
          - "python3"  # EOL Python 3.9
          - "python39"  # EOL Python 3.9
          # - "python311"  # Package 'python311' not found.
          # - "python312"  # No python312-pip
          # - "python312-future"  # Package 'python312-future' not found.
          # - "python312-lxml"  # Package 'python312-lxml' not found.
          - "python312-pip"  # Everything including python312, setuptools, wheel <-- use this!!!
          # - "python312-setuptools"  # No python312-pip
          # - "python312-venv"  # Package 'python312-venv' not found.
          # - "python312-wheel"  # No python312-pip
          # - "python313"  # Package 'python313' not found.
          # - "python314"  # Package 'python314' not found.
    runs-on: windows-latest
    steps:
      - uses: cygwin/cygwin-install-action@v6
        with:
          packages: ${{ matrix.cygwin_package }}
      - run: python3.exe --version || true
        shell: bash
      - run: python3 --version     || true
        shell: bash
      - run: python.exe --version  || true
        shell: bash
      - run: python --version      || true
        shell: bash
      - run: py --version          || true
        shell: bash
      - run: python3 -m pip --version || true
        shell: bash
