# A GitHub Action to demonstrate pip install on Python 3.14t.
# https://github.com/Googulator/pypiwin32 --> https://pypi.org/project/pypiwin32

# % `uvx --with=module python3.14t -c "import module"`

name: free-threading
run-name: free-threading ${{ inputs.pypi_package }}
on:
  workflow_dispatch:
    inputs:
      pypi_package:
        description: 'PyPI package to test'
        required: true
jobs:
  free-threading:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.14t, 3.15, 3.15t]
    runs-on: ${{ matrix.os }}
    env:
      PYPI_PACKAGE: ${{ inputs.pypi_package }}
    steps:
      # Approach two: The terse way: % `uvx --with=module python3.14t -c "import module"`
      - name: "${PYPI_PACKAGE} on python${{ matrix.python-version }}"
        uses: astral-sh/setup-uv@v10.0.1
        with:
          ignore-empty-workdir: true
      # Hyphen to underscore
      - if: inputs.pypi_package == 'clickhouse-connect'
        run: uvx --with=${PYPI_PACKAGE} python${{ matrix.python-version }} -c "import clickhouse_connect"
      - if: inputs.pypi_package == 'scikit-learn'
        run: uvx --with=${PYPI_PACKAGE} python${{ matrix.python-version }} -c "import sklearn"
      - if: inputs.pypi_package == 'MacFSEvents'
        run: uvx --with=${PYPI_PACKAGE} python${{ matrix.python-version }} -c "import fsevents"
      - if: inputs.pypi_package != 'clickhouse-connect' && inputs.pypi_package != 'scikit-learn'
        run: uvx --with=${PYPI_PACKAGE} python${{ matrix.python-version }} -c "import ${PYPI_PACKAGE.replace('-', '_')}"
