# Install standard as end users would do in GitHub Actions.

name: install_standard
on:
  workflow_dispatch
permissions:
  contents: read
jobs:
  install_standard:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - "npm install standard"
          - "yarn add standard"
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: ${{ runner.command }}
