# Install standard as end users would do in GitHub Actions.

name: install_standard
on:
  workflow_dispatch
permissions:
  contents: read
jobs:
  install_standard:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 16.x, 18.x, "lts/*", latest]
        command:
          - "npm install standard"
          - "yarn add standard"
    steps:
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          ${{ matrix.command }}
          standard --version || true  # Fails with: 'standard: command not found'
