name: itinerant_cython_lint_on_demand
run-name: itinerant_cython_lint_on_demand ${{ inputs.repo }}
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo to test (user_name/repo_name)'
        required: true
jobs:
  itinerant_cython_lint_on_demand:
    name: "${{ github.event.inputs.repo }}"
    runs-on: ubuntu-latest
    env:
      REPO: ${{ inputs.repo }}
    steps:
      - run: echo "Testing ${REPO}..."
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          repository: ${REPO}
      - uses: actions/setup-python@v7.0.0
        with:
          python-version: 3.x
      - run: pip install cython-lint  # https://pypi.org/project/com2ann
      - run: cython-lint --version || true
      - run: cython-lint --help
      - run: shopt -s globstar && cython-lint **/*.pyi  # Are .pyi files ignored?
      - run: shopt -s globstar && cython-lint --max-line-length=120 --no-pycodestyle **/*.py[ix] || true
      - run: shopt -s globstar && cython-lint --max-line-length=120 **/*.py[ix]
