name: itinerant_zizmor
run-name: itinerant_zizmor ${{ inputs.repo }}
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'GitHub repo to check with codespell (user_name/repo_name)'
        required: true
jobs:
  itinerant_zizmor:
    runs-on: macos-latest
    steps:
      - run: echo "zizmor Static analysis for GitHub Actions ${{ github.event.inputs.repo }}..."
      - uses: actions/checkout@v7.0.1
        with:
          repository: ${{ github.event.inputs.repo }}
      - run: brew install zizmor
      - run: zizmor --min-severity=high --show-audit-urls=always .
      - run: zizmor --no-exit-codes --show-audit-urls=always .
      - run: |
          zizmor --fix=safe --no-exit-codes --quiet .
          git diff
      - run: |
          zizmor --fix=all --no-exit-codes --quiet .
          git diff
      - run: zizmor --show-audit-urls=always .
