name: itinerant_pytest
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo to test (user_name/repo_name)'
        required: true

jobs:
  itinerant_pytest:
    name: "${{ github.event.inputs.repo }}"
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.x]  # ["3.12", "3.13", "3.14", "pypy-3.11"]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing ${{ github.event.inputs.repo }}..."
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          submodules: recursive
          # ref: dev  # branch, tag, or SHA
      - uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
            allow-prereleases: true
      - run: pip install --upgrade pip
      - run: pip install numpy pytest setuptools  # pymavlink
      - if: github.event.inputs.repo == 'ArduPilot/waf'
        run: cd utils && pip install --editable .
      # - run: mv MAVProxy/modules/mavproxy_test.py MAVProxy/modules/mavproxy_test_module.py
      - name: Install mavlink message
        if: github.event.inputs.repo == 'ArduPilot/pymavlink'
        run: |
          git clone https://github.com/ArduPilot/mavlink.git
          ln -s $PWD/mavlink/message_definitions ../
      - name: Download DSDL Specifications
        if: github.event.inputs.repo == 'dronecan/pydronecan'
        run: |
          git clone https://github.com/DroneCAN/DSDL.git
          ln -s $PWD/DSDL ../
      - if: github.event.inputs.repo == 'ArduPilot/waf'
        run: cd utils && pip install --editable . && pwd
      - run: pwd
      - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: pip install --editable . || pip install pymavlink
      - if: github.event.inputs.repo == 'ArduPilot/waf'
        run: pytest --ignore=playground/genpybind/example_test.py
                    --ignore=playground/pytest/test/test_bar.py
                    --ignore=playground/pytest/test/test_foo.py || true
      - if: github.event.inputs.repo == 'mavlink/mavlink'
        run: pytest --ignore=pymavlink/generator/C/test/posix/sha256_test.py
      - if: github.event.inputs.repo == 'mavlink/MAVSDK-Python'
        run: pip install Jinja2
      - run: pytest
      # - run: ./test_generate_all.sh
      # - run: ./test_generator.sh || true
      - if: github.event.inputs.repo == 'ArduPilot/pymavlink'
        run: rm pytest.ini  # https://github.com/ArduPilot/pymavlink/pull/1062
      - if: github.event.inputs.repo == 'ArduPilot/pymavlink'
        run: pytest --ignore=generator/C/test/posix/sha256_test.py
