name: itinerant_luacheck
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'GitHub repo to lint with luacheck (user_name/repo_name)'
        required: true
jobs:
  itinerant_luacheck:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running luacheck in ${{ github.event.inputs.repo }}..."
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.inputs.repo }}
      # https://github.com/issues/created?issue=lunarmodules%7Cluacheck%7C142 "latest" is v1.0.0
      - if: github.event.inputs.repo == 'ArduPilot/ardupilot'
        run: |
          docker run --rm -v "$PWD:/workdir" -w /workdir ghcr.io/lunarmodules/luacheck:latest lua --version || true
          docker run --rm -v "$PWD:/workdir" -w /workdir ghcr.io/lunarmodules/luacheck:latest luacheck --version || true
          docker run --rm -v "$PWD:/workdir" -w /workdir ghcr.io/lunarmodules/luacheck:latest luacheck --config libraries/AP_Scripting/tests/luacheck.lua .

          docker run --rm -v "$PWD:/workdir" -w /workdir ghcr.io/lunarmodules/luacheck:v1.1.0 lua --version || true
          docker run --rm -v "$PWD:/workdir" -w /workdir ghcr.io/lunarmodules/luacheck:v1.1.0 luacheck --version || true
          docker run --rm -v "$PWD:/workdir" -w /workdir ghcr.io/lunarmodules/luacheck:v1.1.0 luacheck --config libraries/AP_Scripting/tests/luacheck.lua .
    
          docker run --rm -v "$PWD:/workdir" -w /workdir ghcr.io/lunarmodules/luacheck:v1.2.0 lua --version || true
          docker run --rm -v "$PWD:/workdir" -w /workdir ghcr.io/lunarmodules/luacheck:v1.2.0 luacheck --version || true
          docker run --rm -v "$PWD:/workdir" -w /workdir ghcr.io/lunarmodules/luacheck:v1.2.0 luacheck --config libraries/AP_Scripting/tests/luacheck.lua .
        
      - if: github.event.inputs.repo != 'ArduPilot/ardupilot'
        run: |
          docker run --rm -v "$PWD:/workdir" -w /workdir ghcr.io/lunarmodules/luacheck:latest luacheck .
          docker run --rm -v "$PWD:/workdir" -w /workdir ghcr.io/lunarmodules/luacheck:v1.1.0 luacheck .
          docker run --rm -v "$PWD:/workdir" -w /workdir ghcr.io/lunarmodules/luacheck:v1.2.0 luacheck .
        
