name: itinerant_waf
on:
  workflow_dispatch:
jobs:
  itinerant_waf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ArduPilot/waf
          submodules: recursive
          # ref: dev  # branch, tag, or SHA
      - uses: actions/setup-python@v5
        with:
            python-version: 3.9
      - run: pip install --upgrade pip
      - run: pip install pytest setuptools
      - run: pip install --editable ./utils

      - run: python waf-light --tools=buildcopy,genpybind,pytest
      - run: |
          cp waf playground/pytest
          cd playground/pytest
          ./waf configure build --alltests
      - run: PYTHONPATH=playground/pytest/build/src       pytest --ignore=playground/genpybind/example_test.py || true
      - run: PYTHONPATH=build:playground/pytest/build/src pytest --ignore=playground/genpybind/example_test.py || true
      - run:                                              pytest --ignore=playground/genpybind/example_test.py || true
