name: itinerant_zizmor
run-name: itinerant_zizmor ${{ inputs.repo }}
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'GitHub repo to check with codespell (user_name/repo_name).'
        required: true
jobs:
  itinerant_zizmor:
    runs-on: macos-latest
    env:
      REPO: ${{ inputs.repo }}
      ZIZMOR_SHOW_AUDIT_URLS: always
    steps:
      - run: echo "zizmor Static analysis for GitHub Actions ${REPO}..."
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          repository: ${REPO}
      - run: brew install zizmor
      - env:
          CONFIG: "rules:\n  template-injection:\n    disable: true\n  unpinned-uses:\n    disable: true"
        run: echo "$CONFIG" > zizmor.yml && cat zizmor.yml
      - run: zizmor --min-severity=high .
      - env:
          CONFIG: "  excessive-permissions:\n    disable: true"
        run: echo "$CONFIG" >> zizmor.yml && cat zizmor.yml
      - run: zizmor --min-severity=medium .
      #- env:
      #    CONFIG: "  artipacked:\n    disable: true"
      #  run: echo "$CONFIG" >> zizmor.yml && cat zizmor.yml
      - run: zizmor --min-severity=low .
      - run: zizmor --min-severity=informational .
      - run: rm zizmor.yml
      - run: zizmor --no-exit-codes .
      - run: zizmor --fix=safe --no-exit-codes --quiet --quiet --quiet --quiet --quiet --quiet .
      - name: Safe fixable changes to ${{ inputs.repo }}
        run: git diff
      - run: zizmor --fix=all --no-exit-codes --quiet --quiet --quiet --quiet --quiet --quiet .
      - name: All fixable changes to ${{ inputs.repo }}
        run: git diff
      - run: zizmor .
