name: itinerant_pytest
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo to test (user_name/repo_name)'
        required: true

jobs:
  itinerant_pytest:
    name: "${{ github.event.inputs.repo }}"
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]  # tkinter!
    runs-on: ubuntu-24.04  # -arm
    steps:
      - run: echo "Testing ${{ github.event.inputs.repo }}..."
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          submodules: recursive
          # ref: dev  # branch, tag, or SHA
      - uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
            allow-prereleases: true
      # - run: tree
      - run: pip install --upgrade pip
      - run: pip install build pytest dronecan numpy
      - run: pip install -e Tools/autotest/pysim || true
      - run: python -m build || true
      - run: pip install --editable . || true
      - name: Download the DroneCAN DSDL Specifications
        run: |
          git clone https://github.com/DroneCAN/DSDL.git
          ln -s $PWD/DSDL ../
      - run: python -m pytest --version && pytest --version || true
      # - run: pytest --ignore=Tools/FilterTestTool/run_filter_test.py --ignore=Tools/autotest/test_param_upgrade.py || true
      # - run: pytest --ignore=modules/DroneCAN/pydronecan/test/dsdl/test_common.py
      #              --ignore=modules/DroneCAN/pydronecan/test/dsdl/test_load_dsdl.py
      #              --ignore=modules/DroneCAN/pydronecan/test/dsdl/test_parser.py
      #              --ignore=modules/DroneCAN/pydronecan/test/dsdl/test_signature.py
      #              --ignore=modules/DroneCAN/pydronecan/test/test_driver.py
      #              --ignore=modules/DroneCAN/pydronecan/test/test_node.py
      #              --ignore=modules/DroneCAN/pydronecan/test/test_transport.py
      - run: pytest --ignore=modules/gtest/googlemock/test/gmock_leak_test.py
                    --ignore=modules/gtest/googlemock/test/gmock_output_test.py
                    --ignore=modules/gtest/googlemock/test/gmock-function-mocker_nc_test.py
                    --ignore=modules/gtest/googlemock/test/pump_test.py
                    --ignore=modules/gtest/googletest/test/gtest_help_test.py
                    --ignore=modules/gtest/googletest/test/gtest_skip_check_output_test.py
                    --ignore=modules/gtest/googletest/test/gtest_skip_environment_check_output_test.py
                    --ignore=modules/gtest/googletest/test/gtest_testbridge_test.py
                    --ignore=modules/gtest/googletest/test/gtest_xml_outfiles_test.py
                    --ignore=modules/mavlink/pymavlink/generator/C/test/posix/sha256_test.py
                    --ignore=modules/mavlink/pymavlink/tests/snapshottests/test_wlua.py
                    --ignore=modules/mavlink/pymavlink/tests/test_mavlogdump.py
                    --ignore=modules/mavlink/pymavlink/tests/test_mavxml.py
                    --ignore=modules/mavlink/pymavlink/tests/test_quaternion.py
                    --ignore=modules/mavlink/pymavlink/tests/test_rotmat.py
                    --ignore=modules/mavlink/pymavlink/tests/test_trim.py
                    --ignore=modules/mavlink/pymavlink/tests/test_wp.py
                    --ignore=modules/waf/playground/genpybind/example_test.py
                    --ignore=modules/waf/playground/pytest/test/test_bar.py
                    --ignore=modules/waf/playground/pytest/test/test_baz.py
                    --ignore=modules/waf/playground/pytest/test/test_foo.py
                    --ignore=Tools/autotest/test_build_options.py
                    --ignore=Tools/autotest/test_param_upgrade.py
                    --ignore=Tools/FilterTestTool/run_filter_test.py
                    --ignore=Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests
                    --ignore=Tools/ros2/ardupilot_dds_tests/test/test_copyright.py
                    --ignore=Tools/ros2/ardupilot_dds_tests/test/test_pep257.py
                    --ignore=Tools/scripts/build_tests/test_ccache.py
