name: itinerant_codespell
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'GitHub repo to check with codespell (user_name/repo_name)'
        required: true
jobs:
  itinerant_codespell:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Spellchecking ${{ github.event.inputs.repo }}..."
      - uses: actions/checkout@v5
        with:
          repository: ${{ github.event.inputs.repo }}
      - run: pip install --user codespell
      - run: codespell --ignore-words-list="assertin,crate" --count --skip="./.*,*.po,*.svg" --summary  #  --skip="*.css,*.js,*.json,*.lock,*.map,*.po,*.svg"
