name: itinerant_pytest
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo to test (user_name/repo_name)'
        required: true

jobs:
  itinerant_pytest:
    name: "${{ github.event.inputs.repo }}"
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.x]  # ["3.12", "3.13", "3.14", "pypy-3.11"]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing ${{ github.event.inputs.repo }}..."
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          submodules: recursive
          # ref: dev  # branch, tag, or SHA
      - uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
            allow-prereleases: true
      - run: pip install --upgrade pip
      - run: pip install numpy pytest setuptools  # pymavlink
      # - run: mv MAVProxy/modules/mavproxy_test.py MAVProxy/modules/mavproxy_test_module.py
      - name: Install mavlink message
        run: |
          git clone https://github.com/ArduPilot/mavlink.git
          ln -s $PWD/mavlink/message_definitions ../
      - run: pip install --editable .
      - run: ./test_generate_all.sh
      - run: ./test_generator.sh || true
      - run: pytest 
