name: Label PRs by language

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  labels_by_language:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v6
    - uses: actions/github-script@v8
      with:
        script: |
          const files = await github.paginate(github.rest.pulls.listFiles, {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            per_page: 100,
          });

          const filePaths = files.map((file) => file.filename);

          // Map programming languages to their file extensions.
          const languageMap = {
            C: ['.c', '.h'],
            'C++': ['.cpp', '.cc', '.cxx', '.hpp', '.hh', '.hxx'],
            Go: ['.go'],
            JavaScript: ['.js', '.jsx'],
            TypeScript: ['.ts', '.tsx'],
            Lua_: ['.lua'],
            Python_: ['.py', '.pyi'],
            Cython: ['.pyx', '.pxd', '.pxi'],
            Rust: ['.rs'],
          };

          // If any modified file has an extension, then add the label.
          const labels = Object.entries(languageMap)
            .filter(([_, exts]) =>
              exts.some(ext => filePaths.some(path => path.endsWith(ext)))
            )
            .map(([label]) => label);

          if (labels.length > 0) {
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels,
            })
          }

  labels_by_language_short:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v6
    - uses: actions/github-script@v8
      with:
        script: |
          const files = await github.paginate(github.rest.pulls.listFiles, {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            per_page: 100,
          });
          console.log(files);

          const labels = new Set();
          for (const { filename } of files) {
            if (filename.endsWith('.lua')) labels.add('Lua');
            else if (filename.endsWith('.py')) labels.add('Python');
          }
          console.log(labels);

          if (labels.size > 0) {
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: Array.from(labels),
            })
          }
