name: lua_windows
on:
  push:
    paths:
      - '.github/workflows/lua_windows.yml'
  pull_request:
    paths:
      - '.github/workflows/lua_windows.yml'
  workflow_dispatch:
jobs:
  lua_windows:
    permissions:
      contents: read
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        lua_version: ["5.1", "5.2", "5.3", "5.4"]
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: install lua${{ matrix.lua_version }} and luarocks
        shell: bash
        run: |
          NO_DOTS=${{ matrix.lua_version }}
          NO_DOTS=${NO_DOTS//./}  # 5.1.2 --> 512
          # For lua5.4, choco install lua
          if [[ $NO_DOTS == "54" ]]; then
            NO_DOTS=""
          fi
          echo "lua$NO_DOTS"
          choco install lua$NO_DOTS luarocks
          where lua || true
          where lua${{ matrix.lua_version }} || true
