name: luarocks_install
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to test (e.g., moonscript)'
        required: true

jobs:
  luarocks_install:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        lua-version: [5.4, 5.5]  # [5.1, 5.2, 5.3, 5.4, 5.5]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "Installing ${{ github.event.inputs.package }} on ${{ matrix.os }} on ${{ runner.arch }}..."
      - if: runner.os == 'Windows'  # Windows requires the MSVC cl tool.
        uses: step-security/msvc-dev-cmd@v1
      - uses: luarocks/gh-actions-lua@master
        with:
          luaVersion: ${{ matrix.lua-version }}
      - uses: luarocks/gh-actions-luarocks@master
        with:
          luaRocksVersion: "3.13.0"
      - run: lua -v
      - run: luarocks --version
      - run: luarocks --lua-version=${{ matrix.lua-version }} install --check-lua-versions ${{ github.event.inputs.package }} --local
      - run: luarocks --lua-version=${{ matrix.lua-version }} list
      - run: luarocks --lua-version=${{ matrix.lua-version }} show ${{ github.event.inputs.package }}
