# https://github.com/actions/virtual-environments/tree/main/images/macos

name: macOS
on:
  workflow_dispatch:
jobs:
  macOS:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, macos-14, macos-13, macos-latest]
        # arch: [ARM64, X64]  # macos-13 is X64, others are ARM64
    runs-on: ${{ matrix.os }}
    steps:
    - name: ${{ runner.os }} (${{ matrix.os }}) on ${{ runner.arch }}
      run: echo ${{ runner.os }} (${{ matrix.os }}) on ${{ runner.arch }}
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: sw_vers && uname -a && system_profiler SPSoftwareDataType SPHardwareDataType
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
  pythons_on_macOS_12:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: |
          3.12
          3.11
          3.10
          3.9
          3.8
          3.7
    - run: |
        python3.7 --version
        python3.8 --version
        python3.9 --version
        python3.10 --version
        python3.11 --version
        python3.12 --version
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
  pythons_on_macOS_11:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: |
          3.6
          # 3.5
#          3.4
#          3.3
#          3.2
#          3.1
#          3.0
    - run: |
        python3.0 --version || true
        python3.1 --version || true
        python3.2 --version || true
        python3.3 --version || true
        python3.4 --version || true
        python3.5 --version || true
        python3.6 --version || true
        python3.7 --version || true
        python3.8 --version || true
        python3.9 --version || true
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
        python3.10 --version || true
        python3.11 --version || true
        python3.12 --version || true
