name: node_on_three_oses
on: [workflow_dispatch]
jobs:
  node_on_three_oses:
    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        node-version: [23]  # [18, 20, 22, 23]
        os: [macos-13, macos-15, macos-latest, ubuntu-latest, windows-latest, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      # - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      # Temporary workaround for Node.js v22 on Windows
      # - if: ${{ matrix.node-version == '22' && runner.os == 'Windows' }}
      # - if: matrix.node-version == '22' && runner.os == 'Windows'
      #  shell: bash  # Not pwsh!!!
      #  run: |
      #    npm --version  # 10.5.1
      #    npm install -g npm  # >= https://github.com/npm/cli/releases/tag/v10.7.0
      #    npm --version  # 10.7.0 
      # https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - if: runner.os == "Windows"
        run: vswhere -legacy -latest -property installationPath
      - if: runner.os == "Windows"
        run: vswhere -latest -property installationPath
