# A GitHub Action to demonstrate how to run pyaudio on Python 3.13 before its release in Oct. 2024

name: pip_install_pyaudio
on:
  push:
    paths:
      - '.github/workflows/pip_install_pyaudio.yml'
  pull_request:
    paths:
      - '.github/workflows/pip_install_pyaudio.yml'
  workflow_dispatch:
jobs:
  pip_install_pyaudio:
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/CristiFati/pyaudio/blob/master/INSTALL
        os: [ubuntu-latest]  # [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.x, 3.14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Failing step
        id: demo
        if: matrix.python-version == '3.14'
        run: exit 1
      - name: The demo step has failed
        if: ${{ failure() && steps.demo.conclusion == 'failure' && matrix.python-version == '3.14'}}
        run: steps.demo.conclusion = 'success'
      - if: runner.os == 'Linux'
        run: |
          sudo apt-get update -qq
          sudo apt-get install --yes portaudio19-dev # libasound-dev python3-pyaudio
      - if: runner.os == 'macOS'
        run: |
          brew install portaudio
      - if: runner.os == 'Windows'
        shell: bash
        run: |
          systeminfo || true
          vcpkg install portaudio:x86-windows-static
          vcpkg install portaudio:x64-windows-static
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyaudio
