name: pip_install_on_python_prerelease
on:
  workflow_dispatch:
    inputs:
      pagkage:
        description: 'PyPI package to test'
        required: true
      apt_package:
        description: 'apt-get packages to install'
        required: false
jobs:
  pip_install_on_python_prerelease:
    name: "${{ github.event.inputs.pagkage }}"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: 3.14
        allow-prereleases: true
    - if: ${{ github.event.inputs.apt_package }}
      run: |
          sudo apt-get update -qq
          sudo apt-get install --yes ${{ github.event.inputs.apt_package }}
    - run: pip install --upgrade pip
    - run: pip install ${{ github.event.inputs.pagkage }}
