# uvx --with=orjson python3.14t -c "import orjson"

name: pip_install_on_python_prerelease
run-name: pip_install_on_python_prerelease ${{ inputs.pagkage }} with apt install ${{ inputs.apt_package }}
on:
  workflow_dispatch:
    inputs:
      pagkage:
        description: 'PyPI package to test'
        required: true
      apt_package:
        description: 'apt-get packages to install'
        required: false
jobs:
  pip_install_on_python_prerelease:
    runs-on: ubuntu-latest
    env:
      PAGKAGE: ${{ inputs.pagkage }}
      APT_PACKAGE: ${{ inputs.apt_package }}
    steps:
    - uses: actions/checkout@v7.0.1
      with:
        persist-credentials: false
    - uses: actions/setup-python@v7.0.0
      with:
        python-version: 3.15
        allow-prereleases: true
    - if: ${{ inputs.apt_package }}
      run: |
          sudo apt-get update -qq
          sudo apt-get install --yes ${APT_PACKAGE}
    - run: pip install --upgrade pip
    - run: pip install ${PAGKAGE}
