# https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-file-input
# https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
name: python_version_file
on:
  push:
    paths:
      - '.github/workflows/python_version_file.yml'
  pull_request:
    paths:
      - '.github/workflows/python_version_file.yml'
  workflow_dispatch:
jobs:
  total:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ git grep 'export PYVERSION ?=' Makefile.envs | cut -d' ' -f4 }}
      - run: python --version
  get_python_version:
    runs-on: ubuntu-latest
    outputs:
      PYVERSION: ${{ steps.get_python_version.outputs.PYVERSION }}
    steps:
      - uses: actions/checkout@v3
      - id: get_python_version
        run: |
          echo "PYVERSION=$(git grep 'export PYVERSION ?=' Makefile.envs | cut -d' ' -f4)"  >> "$GITHUB_OUTPUT"
  needs_get_python_version:
    runs-on: ubuntu-latest
    needs: get_python_version
    steps:
      - env:
          PYVERSION: ${{needs.get_python_version.outputs.PYVERSION}}
        run: echo "$PYVERSION"
  example_needs:
    runs-on: ubuntu-latest
    outputs:
      python_version: ${{ steps.read_python_version.outputs.python_version }}
    steps:
      - id: read_python_version
        run: echo "python_version=3.7.13" >> "$GITHUB_OUTPUT"
      - run: echo ${{ steps.read_python_version.outputs.python_version }}  # Works
      - env:
          python_version: ${{needs.example_needs.outputs.python_version}}  # Does not work
        run: echo "$python_version"
  reader_needs:
    runs-on: ubuntu-latest
    needs: example_needs
    steps:
      - run: echo ${{ steps.read_python_version.outputs.python_version }}  # Does not work
      - env:
          python_version: ${{needs.example_needs.outputs.python_version}}  # Works!
        run: echo "$python_version"
  example_job:
    runs-on: ubuntu-latest
    steps:
      - shell: python
        run: |
          import os
          with open(os.environ.get('GITHUB_ENV'), "a") as f:
              f.write("test_value=7\n")
          with open(os.environ.get('GITHUB_ENV')) as f:
              for i, line in enumerate(f):
                  print(line)
      - name: set_env
        run: |
          python -c "import os; os.environ['test_value'] = '7'"
      # - run: echo ${{ set_env.env.test_value }}
      - name: Test environment variable
        run: echo $test_value
  reader:
    runs-on: ubuntu-latest
    needs: example_job
    steps:
    - run: echo $test_value
    - run: echo "${{ env.test_value }}"
  example_job_2:
    env:
      bob: "Hello"
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env }}" || true
      - name: set_env_2
        shell: python
        run: |
          import os
          with open(os.environ.get('GITHUB_ENV')) as f:
              for i, line in enumerate(f):
                  print(line)
          # name, value = line.strip().split('=', 1)
          print(0, os.environ["GITHUB_ENV"])
          # os.environ["GITHUB_ENV"] += "test_value=7"
          print(1, os.environ["GITHUB_ENV"])
          os.putenv("GITHUB_ENV", f"{os.environ['GITHUB_ENV']}\ntest_value8=8")
          print(2, os.environ["GITHUB_ENV"])
          with open(os.environ.get('GITHUB_ENV')) as f:
              for i, line in enumerate(f):
                  print(line)
      - run: echo "${{ env }}" || true
      - run: echo "${{ env.test_value }}" || true
      - name: Test environment variable
        run: echo $test_value
  python_version_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read the Python version from Makefile.envs
        shell: python
        run: |
          from pathlib import Path
          lines = Path("Makefile.envs").read_text().splitlines()
          # Looking for a line like: "export PYVERSION ?= 3.11.1"
          python_version = next(
              (line.split()[3] for line in lines if line.startswith("export PYVERSION ?= ")),
              "PYVERSION not found!"
          )
          # Write an ephemeral file because GitHub Actions do not git commit changes
          Path("python-version").write_text(python_version)
      - uses: actions/setup-python@v4
        with:
          python-version-file: "python-version"  # Use the ephemeral file generated above
      - shell: python
        run: import sys ; print(sys.version)
  other:
    runs-on: ubuntu-latest
    needs: python_version_file
    steps:
      - shell: python
        run: import sys ; print(sys.version)
