name: tox
on:  # [push, pull_request]
  push:
    paths:
      - '.github/workflows/tox.yml'
  pull_request:
    paths:
      - '.github/workflows/tox.yml'
  workflow_dispatch:
jobs:
  tox-jobs:
    strategy:
      fail-fast: false
      matrix:
        job: [lint, docs-lint, pycodestyle]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
          # cache: 'pip'  # Only use if there are requirements.txt files
      - run: pip install --upgrade pip
      - run: pip install tox
      - run: tox -e ${{ matrix.job }}

  tox:
    strategy:
      fail-fast: false
      # max-parallel: 4
      matrix:
        os: [ubuntu-latest]  # [macos-latest, ubuntu-latest, windows-latest]
        python: ['3.10', '3.11', '3.12', '3.13', '3.14', 'pypy3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
          # cache: 'pip'
          #python-version: |
          #  3.10
          #  3.11
          #  3.12
          #  3.13
            # 3.14
      - run: python3 --version && python --version
      - run: pip install --upgrade pip
      - run: pip install tox
      - run: tox -e py
      #- run: tox -e py38
      #- run: tox -e py39
      #- run: tox -e py310
      #- run: tox -e py311
      #- run: tox -e ALL
