name: wave_reader
on:
  workflow_dispatch:
jobs:
  wave_reader:
    name: "${{ github.event.inputs.repo }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.11', '3.13']
      max-parallel: 9
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: pip install scipy
      - shell: python
        run: |
          import wave
          from importlib.util import find_spec
          from pathlib import Path
          scipy_path = Path(find_spec("scipy").submodule_search_locations[0])
          wave_filepath = scipy_path / "io/tests/data/test-8000Hz-be-3ch-5S-24bit.wav"
          print(f"{wave_filepath = } {wave_filepath.exists() = }")
          with wave.open(str(wave_filepath)):
              # --> wave.Error: file does not start with RIFF id
              # scipy_path / "io/tests/data/test-8000Hz-be-3ch-5S-24bit.wav" generates the same error.
              pass
